### ISSUE TITLE
Parse token as Authorization: Bearer

### ISSUE THREAD

**Issue by brmzkw** [PlakarKorp/plakar#161]
The syntax `Authorization: <uuid>` is not valid. The proper way to provide a token should be `Authorization: Bearer <uuid>`

**Comment by poolpOrg** [comment]
Can you check that branch [161-parse-token-as-authorization-bearer](https://github.com/PlakarKorp/plakar/tree/161-parse-token-as-authorization-bearer) works for you ?

If so, I'll open the PR and merge, thx

**Comment by brmzkw** [comment]
good!
